### ISSUE TITLE
[test-utils] Don't reference TMP GraphQL schema

### ISSUE THREAD

**Issue by alloy** [microsoft/nova-facade#8]
We should perhaps import the 1GQL schema and augment it locally for now with the pieces needed by AppBar and MeControl?

https://github.com/microsoft/nova-facade/blob/40d05c6fabf319734591ba659bd6821c0cfc206d/packages/nova-react-test-utils/src/test-utils.tsx#L89-L93

**Comment by sjwilczynski** [comment]
@alloy what's the status of this? Does the current implementation mean that to use the test-utils package, one needs to add a dependency on @msteams/data-schema?
